CREATE TABLE IF NOT EXISTS accounts (
    -- GENERATED BY DEFAULT AS IDENTITY (START WITH 1000001) PRIMARY KEY,
    id                      VARCHAR(36)     PRIMARY KEY,
    email                   VARCHAR(255)    NOT NULL UNIQUE,

    enabled                 BOOL            NOT NULL,
    authorities             VARCHAR(255)    NOT NULL,
    account_providers       VARCHAR(255)    NOT NULL,

    confirmation_token      VARCHAR(255),

    password                VARCHAR(255),
    password_reset_token    VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS users (
    id                      VARCHAR(36)     PRIMARY KEY REFERENCES accounts (id),
    first_name              VARCHAR(55),
    last_name               VARCHAR(55)
);

CREATE TABLE IF NOT EXISTS todo_items (
    id                      VARCHAR(36)     PRIMARY KEY,
    user_id                 VARCHAR(36)     NOT NULL REFERENCES accounts (id),
    title                   VARCHAR(255)    NOT NULL,
    description             TEXT,
    status                  VARCHAR(255)    NOT NULL,
    created_at              TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);
